-- Assignment SQL – VI
-- (Join & Sub Query)

-- 1.	Find out the movie number which has been issued to 'ivan'.
-- 2.	Find the names and movie numbers of all the customers who have been issued a movie.
-- 3.	Select the title, cust - id, mv - no for all the movies that are issued.
-- 4.	Find out the title and types of the movies that have been issued to 'Vandana'.
-- 5.	Find the names of customers who have been issued movie of type 'drama'.
-- 6.	Display the title, lname, fname for customers having movie number greater than or equal to three, in the following format:
-- The movie taken by (fname} {lname} is {title}.
-- 7. 	Find out which customers have been issued movie number 9.
-- 8.	Find the customer name and area with invoice number 'i10'.
-- 9.	Find the customer names and phone numbers who have been issued movies before the month of August.
-- 10.	Find the name of the movie issued to 'vandana' and 'ivan'.
-- 11.	List the movie number, movie names issued to all customers.
-- 12.	Find the type and movie number of movie issued to cust – id 'a01' and 'a02'.
-- 13.	Find out if the movie starring' tom cruise' is issued to any customer and print the custid to whom it is issued.
-- 14.	Find the lname, fname who have been issued movies.
-- 15.	Find the name of customer whose has not issued any movie
--